server:
  port: 8086

spring:
  application:
    name: SecurityService

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

cors:
  allowed-origins: http://localhost:63342
  allowed-methods: GET, POST, PUT, DELETE, OPTIONS, PATCH
  allowed-headers: "*"

jwt:
  secret: irineuvocenaosabeenemeujwtsecuritykey
  expiration: 3600000  # 1 hora em milissegundos
